/**
 * The follow-up engine — the Patient Event engine's first real work.
 *
 * FRS §10, two acceptance criteria: "surgery completion creates follow-up" and
 * "red-flag follow-up alerts qualified clinical role". Matrix v2.0 FUP-001,
 * FUP-002 and FUP-003 say the same in activity form, the last at
 * PATIENT_SAFETY with an immediate due rule.
 *
 * ---
 *
 * The design point the requirement is emphatic about: a follow-up response
 * must NOT be a "called" tick. It records pain, swelling, bleeding and
 * medication separately, and then the ENGINE decides whether that combination
 * is dangerous.
 *
 * That division is deliberate and it is the whole value. Whoever rings the
 * patient is usually reception. Asking them to tick "called" throws away
 * everything the patient said; asking them to judge whether it is serious
 * makes a clinical decision the job of somebody without clinical authority.
 * Recording symptoms is within anyone's competence. Deciding they are
 * dangerous is not, so the rule does it — every time, identically, whoever
 * happened to make the call and however busy the morning was.
 */
import { FollowupOutcome, Priority, ExceptionStatus } from '@kubi/contracts';
import type { TenantPrisma } from '../../platform/tenancy/rls-context.js';
import type { Clock } from '../../shared/clock.js';

export class FollowupError extends Error {
  constructor(message: string, readonly code: string) {
    super(message);
    this.name = 'FollowupError';
  }
}

export const Pain = { NONE: 'NONE', MILD: 'MILD', MODERATE: 'MODERATE', SEVERE: 'SEVERE' } as const;
export const Swelling = { EXPECTED: 'EXPECTED', EXCESSIVE: 'EXCESSIVE' } as const;
export const Bleeding = { NO: 'NO', YES: 'YES' } as const;
export const Medication = { TAKING: 'TAKING', PROBLEM: 'PROBLEM' } as const;

export interface FollowupResponse {
  pain: string;
  swelling: string;
  bleeding: string;
  medication: string;
  otherComplaint?: boolean;
}

/**
 * Whether this response needs a clinician, and why in one clause.
 *
 * The requirement's own example is severe pain together with excessive
 * swelling. The others are here because each is independently a reason to look
 * at a post-operative patient, and a rule that only fires on the documented
 * combination would miss the patient who is bleeding but comfortable.
 *
 * Returns the reason rather than a boolean so the alert can say what is wrong.
 * "Red flag" on its own tells a doctor to go and read the record; "severe pain
 * with excessive swelling" tells them what they are walking into.
 */
export function redFlagReason(r: FollowupResponse): string | null {
  if (r.pain === Pain.SEVERE && r.swelling === Swelling.EXCESSIVE) {
    return 'Severe pain with excessive swelling';
  }
  if (r.bleeding === Bleeding.YES) return 'Bleeding reported';
  if (r.swelling === Swelling.EXCESSIVE) return 'Excessive swelling';
  if (r.pain === Pain.SEVERE) return 'Severe pain';
  if (r.medication === Medication.PROBLEM) return 'Problem with medication';
  return null;
}

/**
 * Generate the protocol follow-ups for a completed procedure (FUP-001).
 *
 * Idempotent: called again for the same procedure it creates nothing, because
 * a completion event that arrives twice must not double a patient's calls.
 */
export async function generateFollowups(
  client: TenantPrisma,
  clock: Clock,
  patientProcedureId: string,
): Promise<{ created: number }> {
  const pp = await client.patientProcedure.findUnique({
    where: { id: patientProcedureId },
    include: { procedure: true },
  });
  if (!pp) throw new FollowupError('No such patient procedure.', 'NO_PROCEDURE');
  if (!pp.completedAt) {
    throw new FollowupError(
      'Follow-ups are generated by completion, not before it.',
      'NOT_COMPLETED',
    );
  }

  const existing = await client.followup.findMany({
    where: { patientProcedureId },
    select: { dueAt: true },
  });
  const already = new Set(existing.map((f) => f.dueAt.getTime()));

  const base = pp.completedAt.getTime();
  let created = 0;
  for (const days of pp.procedure.followupOffsetDays) {
    const dueAt = new Date(base + days * 86_400_000);
    if (already.has(dueAt.getTime())) continue;
    await client.followup.create({
      data: {
        organizationId: pp.organizationId,
        clinicId: pp.clinicId,
        patientId: pp.patientId,
        patientProcedureId,
        dueAt,
        outcome: FollowupOutcome.PENDING,
      },
    });
    created += 1;
  }
  return { created };
}

/**
 * Complete a procedure and generate its follow-ups in one step.
 *
 * One call rather than two, because "surgery completion creates follow-up" is
 * a guarantee rather than a convention — a caller that could complete without
 * generating would eventually be written.
 */
export async function completeProcedure(
  client: TenantPrisma,
  clock: Clock,
  patientProcedureId: string,
): Promise<{ created: number }> {
  await client.patientProcedure.update({
    where: { id: patientProcedureId },
    data: { status: 'COMPLETED', completedAt: clock.now() },
  });
  return generateFollowups(client, clock, patientProcedureId);
}

/**
 * Record what the patient said, and let the engine judge it.
 *
 * A red flag raises a PATIENT_SAFETY attention item routed to the clinical
 * side. The Build Pack's escalation table is explicit that patient-safety
 * events start with a qualified clinical owner and escalate to the Clinical
 * Director — not to the manager, who cannot act on it clinically.
 */
export async function recordFollowupResponse(
  client: TenantPrisma,
  clock: Clock,
  followupId: string,
  response: FollowupResponse,
): Promise<{ outcome: string; redFlag: boolean; reason: string | null; attentionItemId?: string }> {
  const followup = await client.followup.findUnique({ where: { id: followupId } });
  if (!followup) throw new FollowupError('No such follow-up.', 'NO_FOLLOWUP');
  if (followup.outcome !== FollowupOutcome.PENDING) {
    throw new FollowupError('That follow-up has already been recorded.', 'ALREADY_RECORDED');
  }

  const reason = redFlagReason(response);
  const outcome = reason
    ? FollowupOutcome.RED_FLAG
    : FollowupOutcome.CONTACTED_WELL;

  let attentionItemId: string | undefined;
  if (reason) {
    const item = await client.attentionItem.create({
      data: {
        organizationId: followup.organizationId,
        clinicId: followup.clinicId,
        code: 'FUP.CLINICAL_RISK.RED_FLAG',
        severity: Priority.PATIENT_SAFETY,
        headline: `Clinical review needed after surgery — ${reason.toLowerCase()}`,
        detail: reason,
        status: ExceptionStatus.OPEN,
        // Immediate. FUP-003's due rule is not a interval, it is "now".
        dueAt: clock.now(),
      },
    });
    attentionItemId = item.id;
  }

  await client.followup.update({
    where: { id: followupId },
    data: {
      outcome,
      pain: response.pain,
      swelling: response.swelling,
      bleeding: response.bleeding,
      medication: response.medication,
      otherComplaint: response.otherComplaint ?? false,
      redFlag: reason !== null,
      redFlagReason: reason,
      escalatedItemId: attentionItemId ?? null,
      contactedAt: clock.now(),
    },
  });

  return { outcome, redFlag: reason !== null, reason, ...(attentionItemId ? { attentionItemId } : {}) };
}

/** A follow-up nobody could reach. Recorded as its own outcome, never as well. */
export async function recordNoResponse(
  client: TenantPrisma,
  clock: Clock,
  followupId: string,
): Promise<void> {
  await client.followup.update({
    where: { id: followupId },
    data: { outcome: FollowupOutcome.NO_RESPONSE, contactedAt: clock.now() },
  });
}

/** Follow-ups due now, oldest first — the list reception works from. */
export async function dueFollowups(
  client: TenantPrisma,
  clock: Clock,
  clinicId: string,
) {
  return client.followup.findMany({
    where: {
      clinicId,
      outcome: FollowupOutcome.PENDING,
      dueAt: { lte: clock.now() },
    },
    orderBy: { dueAt: 'asc' },
    include: { patientProcedure: { include: { procedure: { select: { name: true } } } } },
  });
}
