/**
 * The activity library — GENERATED. Do not edit.
 *
 * Source: docs/requirements/master-activity-matrix-v2.tsv
 * Regenerate: node scripts/build-activity-library.mjs
 *
 * 101 activities, 0 shipping DISABLED because the
 * frozen matrix has no due rule for them. A guessed schedule would be worse
 * than an absent one: it would look like a decision somebody made.
 *
 * This file is the PSS engine's data. The matrix's own columns are the
 * hierarchy — function, sub-function, activity, the four responsibilities, the
 * escalation ladder, evidence, KPI, automation rule, failure definition and
 * CAPA obligation — so none of it is authored here.
 */

export interface LibraryActivity {
  id: string;
  /** Function — the control parameter this belongs to. */
  fn: string;
  /** Sub-function — the process it sits in. */
  subFn: string | null;
  subProcess: string | null;
  activity: string;
  standard: string | null;
  trigger: string | null;
  frequency: string | null;
  /** Null means nobody has decided. The activity ships disabled. */
  dueRule: string | null;
  /** One of the five object types. */
  origin: string;
  /** Which of the six engines raises it. */
  engine: string;
  doer: string | null;
  /** Null permits self-verification. Never means nobody checks. */
  checker: string | null;
  owner: string | null;
  /** L1 → L2 → L3, in order. */
  escalation: string[];
  priority: string | null;
  evidenceType: string | null;
  evidenceRequired: string | null;
  dependency: string | null;
  automationRule: string | null;
  failure: string | null;
  kpi: string | null;
  capa: string | null;
  enabled: boolean;
}

export const ACTIVITY_LIBRARY: readonly LibraryActivity[] = [
  {
    "id": "ATT-001",
    "fn": "Attendance & Leave",
    "subFn": "Attendance",
    "subProcess": "Daily Attendance",
    "activity": "Report for duty",
    "standard": "All scheduled staff checked in by 09:45",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "09:45",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "All Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Employee",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Check-in timestamp",
    "dependency": null,
    "automationRule": "Late/absence detection",
    "failure": "Check-in after deadline",
    "kpi": "On-Time Attendance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "ATT-002",
    "fn": "Attendance & Leave",
    "subFn": "Attendance",
    "subProcess": "Daily Attendance",
    "activity": "Record checkout",
    "standard": "All present staff record end-of-shift checkout",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Shift end",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "All Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Employee",
      "Manager",
      "Clinic Head"
    ],
    "priority": "ROUTINE",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Checkout timestamp",
    "dependency": null,
    "automationRule": "Missing checkout alert",
    "failure": "No checkout",
    "kpi": "Attendance Record Completeness %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "ATT-003",
    "fn": "Attendance & Leave",
    "subFn": "Attendance",
    "subProcess": "Daily Attendance",
    "activity": "Submit planned leave",
    "standard": "Planned leave submitted in advance per policy",
    "trigger": "MANUAL",
    "frequency": "AS_REQUIRED",
    "dueRule": "Policy-defined",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Employee",
    "checker": "Reporting Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Employee",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Leave request",
    "dependency": "Leave policy",
    "automationRule": "Approval workflow",
    "failure": "Insufficient notice/unapproved leave",
    "kpi": "Planned Leave Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "ATT-004",
    "fn": "Attendance & Leave",
    "subFn": "Attendance",
    "subProcess": "Daily Attendance",
    "activity": "Approve/reject leave",
    "standard": "Every submitted leave has disposition and coverage check",
    "trigger": "EVENT",
    "frequency": "AS_REQUIRED",
    "dueRule": "Before leave",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reporting Manager",
    "checker": "Clinic Head",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Decision",
    "dependency": "Leave submitted",
    "automationRule": "Approval notification",
    "failure": "Pending beyond SLA",
    "kpi": "Leave Approval SLA %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "OPN-001",
    "fn": "Opening Readiness",
    "subFn": "Opening",
    "subProcess": "Clinic Opening",
    "activity": "Open clinic/floors",
    "standard": "Required clinic areas opened before first patient",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Before first patient",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Opening Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Opening checklist",
    "dependency": null,
    "automationRule": "Generate opening checklist",
    "failure": "Area not opened",
    "kpi": "Opening On-Time %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "OPN-002",
    "fn": "Opening Readiness",
    "subFn": "Opening",
    "subProcess": "Clinic Opening",
    "activity": "Treatment room readiness",
    "standard": "All scheduled operatories clean, stocked and functional",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Before first patient",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Dental Assistant",
    "checker": "Senior Assistant",
    "owner": "Clinic Manager",
    "escalation": [
      "Assistant",
      "Senior Assistant",
      "Manager"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Room checklist",
    "dependency": "Chair/equipment status",
    "automationRule": "Readiness aggregation",
    "failure": "Room not ready",
    "kpi": "Room Readiness %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "OPN-003",
    "fn": "Opening Readiness",
    "subFn": "Opening",
    "subProcess": "Clinic Opening",
    "activity": "Reception readiness",
    "standard": "Phones, appointment list, payment/reception systems ready",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Before first patient",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Reception checklist",
    "dependency": null,
    "automationRule": "Generate task",
    "failure": "Reception not ready",
    "kpi": "Reception Readiness %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "OPN-004",
    "fn": "Opening Readiness",
    "subFn": "Opening",
    "subProcess": "Clinic Opening",
    "activity": "Environment readiness",
    "standard": "AC 24°C where applicable, diffuser/lights as schedule",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Opening",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Housekeeping/Assistant",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "ROUTINE",
    "evidenceType": "VALUE",
    "evidenceRequired": "Checklist/value",
    "dependency": null,
    "automationRule": "Generate task",
    "failure": "Environment outside standard",
    "kpi": "Environment Compliance %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "OPN-005",
    "fn": "Opening Readiness",
    "subFn": "Opening",
    "subProcess": "Clinic Opening",
    "activity": "Emergency readiness quick check",
    "standard": "Emergency equipment/critical items available and accessible",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Opening",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Assistant",
    "checker": "Doctor/Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Pass/fail",
    "dependency": "Emergency inventory",
    "automationRule": "Block/exception if fail",
    "failure": "Critical emergency item unavailable",
    "kpi": "Emergency Readiness %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "APT-001",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "Confirm today's patients",
    "standard": "All today's patients contacted/confirmed early morning",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Morning",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Contact outcome",
    "dependency": "Today's appointments",
    "automationRule": "Generate confirmation queue",
    "failure": "Unresolved confirmation",
    "kpi": "Confirmation %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "APT-002",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "Retry no-response confirmations",
    "standard": "Configured retry attempts completed",
    "trigger": "EVENT",
    "frequency": "DAILY",
    "dueRule": "Before appointment",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Call log",
    "dependency": "No response",
    "automationRule": "Retry workflow",
    "failure": "Retry not completed",
    "kpi": "Confirmation Resolution %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "APT-003",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "Review reminders and recalls",
    "standard": "Due reminders/recalls actioned",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Morning",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "ROUTINE",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Communication log",
    "dependency": null,
    "automationRule": "Generate queue",
    "failure": "Due reminder missed",
    "kpi": "Recall Contact %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "APT-004",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "Patient arrival registration",
    "standard": "Arrival recorded and record verified",
    "trigger": "EVENT",
    "frequency": "PER_PATIENT",
    "dueRule": "At arrival",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Arrival timestamp",
    "dependency": "Appointment/patient",
    "automationRule": "Patient flow transition",
    "failure": "Arrival not recorded",
    "kpi": "Registration Completeness %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "APT-005",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "Manage waiting patient",
    "standard": "Waiting time monitored against threshold",
    "trigger": "THRESHOLD",
    "frequency": "CONTINUOUS",
    "dueRule": "Configured minutes",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reception",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Wait timestamp",
    "dependency": "Arrival",
    "automationRule": "Wait alert",
    "failure": "Wait exceeds threshold",
    "kpi": "Average Waiting Time",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "APT-006",
    "fn": "Appointments & Reception",
    "subFn": "Appointment Management",
    "subProcess": "Daily Schedule",
    "activity": "No-show handling",
    "standard": "No-show recorded and follow-up workflow initiated",
    "trigger": "DEADLINE",
    "frequency": "PER_APPOINTMENT",
    "dueRule": "After grace period",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Status/contact log",
    "dependency": "Scheduled appointment",
    "automationRule": "No-show workflow",
    "failure": "No-show not actioned",
    "kpi": "No-Show Recovery %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "CLN-001",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Update medical history",
    "standard": "Medical history current before applicable treatment",
    "trigger": "EVENT",
    "frequency": "PER_VISIT",
    "dueRule": "Before treatment",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Doctor/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Current history",
    "dependency": "Patient visit",
    "automationRule": "Readiness gate",
    "failure": "History not current",
    "kpi": "Medical History Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "CLN-002",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Verify procedure consent",
    "standard": "Valid procedure-specific consent signed",
    "trigger": "DEPENDENCY",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before procedure",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Doctor/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SIGNATURE",
    "evidenceRequired": "Signed consent",
    "dependency": "Procedure requires consent",
    "automationRule": "Consent gate",
    "failure": "Consent absent",
    "kpi": "Consent Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "CLN-003",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Pre-treatment scan/photo",
    "standard": "Required baseline scan/photo documented",
    "trigger": "EVENT",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before procedure",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Assistant/Doctor",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doer",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Image/scan",
    "dependency": "Procedure protocol",
    "automationRule": "Documentation gate",
    "failure": "Required baseline missing",
    "kpi": "Pre-Treatment Documentation %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-004",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Verify radiograph requirement",
    "standard": "Required radiograph available/current",
    "trigger": "DEPENDENCY",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before procedure",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Doctor",
    "checker": "Clinical Director",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Radiograph reference",
    "dependency": "Procedure protocol",
    "automationRule": "Readiness gate",
    "failure": "Required radiograph missing",
    "kpi": "Radiograph Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "CLN-005",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Chairside setup",
    "standard": "Procedure-specific instruments/materials ready",
    "trigger": "EVENT",
    "frequency": "PER_PATIENT",
    "dueRule": "Before seating/procedure",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Dental Assistant",
    "checker": "Doctor",
    "owner": "Clinic Manager",
    "escalation": [
      "Assistant",
      "Doctor",
      "Manager"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Setup checklist",
    "dependency": "Procedure plan",
    "automationRule": "Generate setup task",
    "failure": "Required item missing",
    "kpi": "Chairside Readiness %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-006",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Pre-op medication reminder",
    "standard": "Surgical patient reminded per prescribed plan",
    "trigger": "TIME",
    "frequency": "PER_SURGERY",
    "dueRule": "Protocol-defined",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Reception",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Contact acknowledgement",
    "dependency": "Surgery scheduled",
    "automationRule": "Reminder automation",
    "failure": "Reminder not completed",
    "kpi": "Pre-op Reminder Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-007",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Pre-op meal/instruction reminder",
    "standard": "Surgical patient receives clinic-approved pre-op instructions",
    "trigger": "TIME",
    "frequency": "PER_SURGERY",
    "dueRule": "Protocol-defined",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Reception",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Acknowledgement",
    "dependency": "Surgery scheduled",
    "automationRule": "Reminder automation",
    "failure": "Instruction not acknowledged",
    "kpi": "Pre-op Instruction Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-008",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Procedure readiness evaluation",
    "standard": "All mandatory configured requirements evaluated",
    "trigger": "DEPENDENCY",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before start",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "System",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Treating Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Readiness result",
    "dependency": "All readiness inputs",
    "automationRule": "Evaluate gate",
    "failure": "NOT_READY",
    "kpi": "Procedure Readiness %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "CLN-009",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Post-treatment scan/photo",
    "standard": "Required post-treatment record captured",
    "trigger": "EVENT",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before visit closure",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Assistant/Doctor",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doer",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Image/scan",
    "dependency": "Procedure protocol",
    "automationRule": "Documentation task",
    "failure": "Required post record missing",
    "kpi": "Post-Treatment Documentation %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-010",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Post-op instructions",
    "standard": "Applicable patient receives documented instructions",
    "trigger": "EVENT",
    "frequency": "PER_PROCEDURE",
    "dueRule": "Before discharge",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Doctor/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doer",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Instruction acknowledgement",
    "dependency": "Procedure completed",
    "automationRule": "Discharge gate",
    "failure": "Instructions not documented",
    "kpi": "Post-op Instruction Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLN-011",
    "fn": "Patient Care & Clinical",
    "subFn": "Clinical Readiness",
    "subProcess": "Pre-Treatment",
    "activity": "Clinical notes completion",
    "standard": "Required clinical note completed",
    "trigger": "DEADLINE",
    "frequency": "PER_VISIT",
    "dueRule": "Before/within configured SLA",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Treating Doctor",
    "checker": "Clinical Director",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Completed note",
    "dependency": "Visit",
    "automationRule": "Documentation exception",
    "failure": "Note incomplete",
    "kpi": "Clinical Note Completion %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "FUP-001",
    "fn": "Patient Follow-up",
    "subFn": "Follow-up",
    "subProcess": "Post-Treatment",
    "activity": "Generate surgical follow-up",
    "standard": "Protocol follow-up auto-created after surgery",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_SURGERY",
    "dueRule": "At completion",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "System",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception Lead",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Generated task",
    "dependency": "Surgery completed",
    "automationRule": "Auto-create follow-up",
    "failure": "Follow-up not generated",
    "kpi": "Follow-up Generation %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "FUP-002",
    "fn": "Patient Follow-up",
    "subFn": "Follow-up",
    "subProcess": "Post-Treatment",
    "activity": "Day-after surgery call",
    "standard": "Surgery patient contacted next day",
    "trigger": "TIME",
    "frequency": "PER_SURGERY",
    "dueRule": "+1 day",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doer",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Outcome/questionnaire",
    "dependency": "Follow-up due",
    "automationRule": "Reminder/escalation",
    "failure": "Call overdue",
    "kpi": "Surgery Follow-up Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "FUP-003",
    "fn": "Patient Follow-up",
    "subFn": "Follow-up",
    "subProcess": "Post-Treatment",
    "activity": "Escalate red flags",
    "standard": "Configured symptoms routed to qualified clinician",
    "trigger": "EVENT",
    "frequency": "PER_FOLLOWUP",
    "dueRule": "Immediate",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "System",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Treating Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Alert acknowledgement",
    "dependency": "Red-flag response",
    "automationRule": "Clinical alert",
    "failure": "Alert unacknowledged",
    "kpi": "Clinical Alert Response Time",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "FUP-004",
    "fn": "Patient Follow-up",
    "subFn": "Follow-up",
    "subProcess": "Post-Treatment",
    "activity": "Treatment progress follow-up",
    "standard": "Protocol review/follow-up completed",
    "trigger": "TIME",
    "frequency": "PER_PROTOCOL",
    "dueRule": "Protocol-defined",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception/Doctor",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doer",
      "Doctor",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Outcome",
    "dependency": "Procedure protocol",
    "automationRule": "Generate due task",
    "failure": "Follow-up overdue",
    "kpi": "Follow-up Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "FUP-005",
    "fn": "Patient Follow-up",
    "subFn": "Follow-up",
    "subProcess": "Post-Treatment",
    "activity": "Google review request",
    "standard": "Eligible completed patient asked for review",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_TREATMENT",
    "dueRule": "After completion",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Reception",
    "checker": "Reception Lead",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Lead",
      "Manager"
    ],
    "priority": "ROUTINE",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Request sent",
    "dependency": "Treatment completed/eligibility",
    "automationRule": "Generate request",
    "failure": "Eligible request missed",
    "kpi": "Review Request %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "LAB-001",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Create lab case",
    "standard": "All sent work has complete digital lab record",
    "trigger": "EVENT",
    "frequency": "PER_CASE",
    "dueRule": "Before dispatch",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Lab Coordinator/Assistant",
    "checker": "Doctor",
    "owner": "Clinic Manager",
    "escalation": [
      "Coordinator",
      "Doctor",
      "Manager"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Case record",
    "dependency": "Lab work prescribed",
    "automationRule": "Case workflow",
    "failure": "Incomplete case record",
    "kpi": "Lab Record Completeness %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "LAB-002",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Dispatch lab case",
    "standard": "Dispatch date/materials recorded",
    "trigger": "EVENT",
    "frequency": "PER_CASE",
    "dueRule": "At dispatch",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Lab Coordinator",
    "checker": "Doctor",
    "owner": "Clinic Manager",
    "escalation": [
      "Coordinator",
      "Doctor",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Dispatch record",
    "dependency": "Case created",
    "automationRule": "Status transition",
    "failure": "Unrecorded dispatch",
    "kpi": "Lab Dispatch Compliance %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "LAB-003",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Monitor expected return",
    "standard": "Cases tracked against due date",
    "trigger": "DEADLINE",
    "frequency": "DAILY",
    "dueRule": "Before due date",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Lab Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Coordinator",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Status",
    "dependency": "Expected return date",
    "automationRule": "Due/overdue alerts",
    "failure": "Case overdue",
    "kpi": "On-Time Lab %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "LAB-004",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Receive and cross-check case",
    "standard": "Received work matched to case/patient/specification",
    "trigger": "EVENT",
    "frequency": "PER_CASE",
    "dueRule": "At receipt",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Lab Coordinator",
    "checker": "Doctor",
    "owner": "Clinic Manager",
    "escalation": [
      "Coordinator",
      "Doctor",
      "Manager"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Receipt/check",
    "dependency": "Lab received",
    "automationRule": "Generate QC",
    "failure": "Mismatch/missing item",
    "kpi": "Lab Receipt Accuracy %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "LAB-005",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Doctor QC",
    "standard": "Clinical/lab QC completed before patient-ready",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_CASE",
    "dueRule": "After receipt",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Doctor",
    "checker": "Clinical Lead",
    "owner": "Clinical Director",
    "escalation": [
      "Lab Coordinator",
      "Clinical Lead",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "QC result",
    "dependency": "Case received",
    "automationRule": "QC gate",
    "failure": "QC pending/failed",
    "kpi": "Lab QC Pass %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "LAB-006",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Schedule after readiness",
    "standard": "Patient delivery appointment only after configured lab readiness",
    "trigger": "DEPENDENCY",
    "frequency": "PER_CASE",
    "dueRule": "After QC pass",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Reception",
    "checker": "Lab Coordinator",
    "owner": "Clinic Manager",
    "escalation": [
      "Reception",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Appointment link",
    "dependency": "QC passed",
    "automationRule": "Scheduling gate",
    "failure": "Appointment created too early",
    "kpi": "Lab-Ready Scheduling Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "LAB-007",
    "fn": "Laboratory Management",
    "subFn": "Lab Case",
    "subProcess": "Tracking & QC",
    "activity": "Manage remake/correction",
    "standard": "Failed QC creates correction/remake workflow",
    "trigger": "EVENT",
    "frequency": "PER_CASE",
    "dueRule": "Immediate",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Lab Coordinator",
    "checker": "Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Coordinator",
      "Doctor",
      "Clinical Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Reason/action",
    "dependency": "QC failed",
    "automationRule": "Create correction/remake",
    "failure": "Failure unresolved",
    "kpi": "Lab Remake %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "STER-001",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Collect used instruments",
    "standard": "Used instruments moved into dirty workflow safely",
    "trigger": "EVENT",
    "frequency": "PER_BATCH",
    "dueRule": "After use",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Dental Assistant",
    "checker": "Senior Assistant",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Senior Assistant",
      "Clinical Director"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Batch record",
    "dependency": "Instrument use",
    "automationRule": "Create batch",
    "failure": "Used instruments untracked",
    "kpi": "Instrument Traceability %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-002",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Ultrasonic cleaning",
    "standard": "Required instruments ultrasonically cleaned same day",
    "trigger": "EVENT",
    "frequency": "PER_BATCH",
    "dueRule": "Same day",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Dental Assistant",
    "checker": "Senior Assistant",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Senior Assistant",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Stage timestamp",
    "dependency": "Batch collected",
    "automationRule": "Stage workflow",
    "failure": "Cleaning not completed",
    "kpi": "Same-Day Processing %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-003",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Inspect/dry/pack",
    "standard": "Instruments inspected and properly sealed/packed",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_BATCH",
    "dueRule": "After cleaning",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Dental Assistant",
    "checker": "Senior Assistant",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Senior Assistant",
      "Clinical Director"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Pack record",
    "dependency": "Cleaning complete",
    "automationRule": "Stage gate",
    "failure": "Improper/unsealed pack",
    "kpi": "Packing Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-004",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Autoclave cycle",
    "standard": "Cycle parameters/result recorded",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_BATCH",
    "dueRule": "Same day",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Dental Assistant",
    "checker": "Senior Assistant",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Senior Assistant",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VALUE",
    "evidenceRequired": "Cycle result",
    "dependency": "Packing complete",
    "automationRule": "Cycle gate",
    "failure": "Cycle failed",
    "kpi": "Autoclave Pass %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-005",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Release sterile packs",
    "standard": "Only passed verified batches released",
    "trigger": "DEPENDENCY",
    "frequency": "PER_BATCH",
    "dueRule": "After pass",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Senior Assistant",
    "checker": "Doctor/Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Senior Assistant",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Release record",
    "dependency": "Cycle PASS",
    "automationRule": "Release gate",
    "failure": "Release without valid pass",
    "kpi": "Sterile Release Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-006",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Closing pending instrument check",
    "standard": "No used instruments remain unprocessed at closing",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Senior Assistant",
    "checker": "Clinic Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Senior Assistant",
      "Manager",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Pending count",
    "dependency": "End of day",
    "automationRule": "Critical exception",
    "failure": "Pending used instruments",
    "kpi": "Same-Day Sterilization %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "STER-007",
    "fn": "Infection Control",
    "subFn": "Sterilization",
    "subProcess": "Instrument Cycle",
    "activity": "Biomedical waste disposal",
    "standard": "Waste segregated/disposed on schedule",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Configured",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Assistant/Housekeeping",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Waste checklist",
    "dependency": null,
    "automationRule": "Generate task",
    "failure": "Waste not disposed/segregated",
    "kpi": "BMW Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-001",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Daily critical consumable check",
    "standard": "Critical room consumables available",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Opening",
    "origin": "RECURRING",
    "engine": "INVENTORY",
    "doer": "Dental Assistant",
    "checker": "Inventory Coordinator",
    "owner": "Clinic Manager",
    "escalation": [
      "Assistant",
      "Inventory",
      "Manager"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Checklist",
    "dependency": "Room readiness",
    "automationRule": "Low-stock alert",
    "failure": "Critical consumable missing",
    "kpi": "Critical Consumable Availability %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-002",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Record stock receipt",
    "standard": "All received stock entered by batch/expiry where applicable",
    "trigger": "EVENT",
    "frequency": "PER_RECEIPT",
    "dueRule": "At receipt",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Inventory Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "GRN/receipt",
    "dependency": "PO/receipt",
    "automationRule": "Update stock",
    "failure": "Receipt not recorded",
    "kpi": "Receipt Accuracy %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "INV-003",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Record stock issue",
    "standard": "Material issues recorded through controlled transaction",
    "trigger": "EVENT",
    "frequency": "AS_USED",
    "dueRule": "At issue",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Authorized Staff",
    "checker": "Inventory Coordinator",
    "owner": "Clinic Manager",
    "escalation": [
      "User",
      "Inventory",
      "Manager"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Stock transaction",
    "dependency": "Available stock",
    "automationRule": "Update stock",
    "failure": "Unrecorded/negative stock",
    "kpi": "Stock Transaction Accuracy %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-004",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Low-stock reorder",
    "standard": "Reorder action generated at configured threshold",
    "trigger": "THRESHOLD",
    "frequency": "CONTINUOUS",
    "dueRule": "Immediate",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "System/Inventory Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Alert/PR",
    "dependency": "Stock <= reorder",
    "automationRule": "Create PR/alert",
    "failure": "Threshold without action",
    "kpi": "Stock-Out Rate",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-005",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Expiry monitoring",
    "standard": "Near-expiry batches surfaced and FEFO applied",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Configured horizon",
    "origin": "RECURRING",
    "engine": "INVENTORY",
    "doer": "System/Inventory Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Expiry report",
    "dependency": "Batch expiry",
    "automationRule": "Expiry alerts",
    "failure": "Expired stock treated usable",
    "kpi": "Expiry/Wastage %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-006",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Purchase request approval",
    "standard": "PR approved/rejected per authority matrix",
    "trigger": "EVENT",
    "frequency": "PER_PR",
    "dueRule": "Within SLA",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Approver",
    "checker": "Clinic Head",
    "owner": "Owner/Clinic Head",
    "escalation": [
      "Approver",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Approval record",
    "dependency": "PR submitted",
    "automationRule": "Approval workflow",
    "failure": "PR overdue",
    "kpi": "PR Approval SLA %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "INV-007",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Goods receipt reconciliation",
    "standard": "Received quantities matched to PO/PR",
    "trigger": "EVENT",
    "frequency": "PER_RECEIPT",
    "dueRule": "At receipt",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Inventory Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "GRN",
    "dependency": "PO exists",
    "automationRule": "Reconcile variance",
    "failure": "Quantity/price mismatch",
    "kpi": "GRN Accuracy %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INV-008",
    "fn": "Inventory & Procurement",
    "subFn": "Inventory",
    "subProcess": "Stock Control",
    "activity": "Wastage/adjustment control",
    "standard": "All wastage/adjustments have reason and authorization",
    "trigger": "EVENT",
    "frequency": "AS_REQUIRED",
    "dueRule": "At event",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Authorized Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "User",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Reason/approval",
    "dependency": "Stock transaction",
    "automationRule": "Audit alert",
    "failure": "Unexplained adjustment",
    "kpi": "Inventory Variance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "IMP-001",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Maintain implant SKU master",
    "standard": "Manufacturer/system/platform/dimensions/components current",
    "trigger": "MANUAL",
    "frequency": "AS_REQUIRED",
    "dueRule": "Before use",
    "origin": "CONDITION",
    "engine": "INVENTORY",
    "doer": "Implant Coordinator",
    "checker": "Clinical Director",
    "owner": "Clinical Director",
    "escalation": [
      "Coordinator",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Master record",
    "dependency": null,
    "automationRule": "Master validation",
    "failure": "Missing/invalid SKU data",
    "kpi": "Implant Master Completeness %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "IMP-002",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Upcoming surgery requirements",
    "standard": "Planned implant/components captured per case",
    "trigger": "EVENT",
    "frequency": "PER_SURGERY",
    "dueRule": "Before surgery",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Treating Doctor",
    "checker": "Implant Coordinator",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Case requirement",
    "dependency": "Surgery scheduled",
    "automationRule": "Generate readiness",
    "failure": "Requirements incomplete",
    "kpi": "Implant Planning Completeness %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "IMP-003",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Implant stock readiness",
    "standard": "Required implant/components compared to usable stock",
    "trigger": "DEPENDENCY",
    "frequency": "PER_SURGERY",
    "dueRule": "Configured lead time",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "System/Implant Coordinator",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Coordinator",
      "Doctor",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Readiness result",
    "dependency": "Case requirements",
    "automationRule": "Shortage alert",
    "failure": "Missing required stock",
    "kpi": "Implant Readiness %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "IMP-004",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Implant lot/expiry verification",
    "standard": "Selected implant batch valid and not expired",
    "trigger": "DEPENDENCY",
    "frequency": "PER_IMPLANT",
    "dueRule": "Before use",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Assistant/Doctor",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Batch/expiry",
    "dependency": "Implant selected",
    "automationRule": "Use gate",
    "failure": "Expired/invalid batch",
    "kpi": "Valid Implant Batch %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "IMP-005",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Record implant usage",
    "standard": "Patient/site/SKU/lot/dimensions/doctor permanently linked",
    "trigger": "EVENT",
    "frequency": "PER_IMPLANT",
    "dueRule": "At placement",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Treating Doctor/Assistant",
    "checker": "Treating Doctor",
    "owner": "Clinical Director",
    "escalation": [
      "Doctor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Usage record",
    "dependency": "Procedure",
    "automationRule": "Decrement stock",
    "failure": "Traceability incomplete",
    "kpi": "Implant Traceability %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "IMP-006",
    "fn": "Implant Inventory",
    "subFn": "Implant Control",
    "subProcess": "Readiness & Traceability",
    "activity": "Implant stock reconciliation",
    "standard": "Physical vs system implant stock reconciled",
    "trigger": "TIME",
    "frequency": "WEEKLY",
    "dueRule": "Week end",
    "origin": "RECURRING",
    "engine": "INVENTORY",
    "doer": "Implant Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Coordinator",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Count/reconciliation",
    "dependency": null,
    "automationRule": "Variance exception",
    "failure": "Unexplained variance",
    "kpi": "Implant Inventory Accuracy %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "EQP-001",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Daily functional check",
    "standard": "Critical assets checked before clinical use",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Opening",
    "origin": "RECURRING",
    "engine": "EQUIPMENT",
    "doer": "Assigned Assistant",
    "checker": "Clinic Manager",
    "owner": "Clinic Manager",
    "escalation": [
      "Asset Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Pass/fail",
    "dependency": "Asset active",
    "automationRule": "Failure workflow",
    "failure": "Functional check failed",
    "kpi": "Equipment Availability %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EQP-002",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Preventive maintenance scheduling",
    "standard": "PM task generated before due date",
    "trigger": "TIME",
    "frequency": "PER_PLAN",
    "dueRule": "Lead-time configured",
    "origin": "RECURRING",
    "engine": "EQUIPMENT",
    "doer": "System",
    "checker": "Equipment Owner",
    "owner": "Clinic Manager",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "PM task",
    "dependency": "Maintenance plan",
    "automationRule": "Generate task",
    "failure": "PM not generated",
    "kpi": "PM Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "EQP-003",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Complete preventive maintenance",
    "standard": "PM completed with service evidence",
    "trigger": "DEADLINE",
    "frequency": "PER_PLAN",
    "dueRule": "By due date",
    "origin": "CONDITION",
    "engine": "EQUIPMENT",
    "doer": "Equipment Owner/Vendor",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Service record",
    "dependency": "PM due",
    "automationRule": "Overdue exception",
    "failure": "PM overdue",
    "kpi": "PM Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "EQP-004",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Calibration control",
    "standard": "Calibration completed before expiry where required",
    "trigger": "TIME",
    "frequency": "PER_PLAN",
    "dueRule": "Before due",
    "origin": "RECURRING",
    "engine": "EQUIPMENT",
    "doer": "Equipment Owner",
    "checker": "Clinic Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Calibration certificate",
    "dependency": "Calibration plan",
    "automationRule": "Restrict if overdue",
    "failure": "Calibration overdue",
    "kpi": "Calibration Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EQP-005",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Breakdown reporting",
    "standard": "Failure creates breakdown ticket and asset restriction",
    "trigger": "EVENT",
    "frequency": "PER_FAILURE",
    "dueRule": "Immediate",
    "origin": "CONDITION",
    "engine": "EQUIPMENT",
    "doer": "Any Authorized User",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Reporter",
      "Manager",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Breakdown record",
    "dependency": "Functional failure",
    "automationRule": "Restrict asset/notify",
    "failure": "Failure not ticketed",
    "kpi": "Breakdown Reporting Time",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EQP-006",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "Return to service",
    "standard": "Repaired asset independently verified before availability",
    "trigger": "DEPENDENCY",
    "frequency": "PER_BREAKDOWN",
    "dueRule": "After repair",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Equipment Owner/Vendor",
    "checker": "Clinic Manager/Qualified Verifier",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Verifier",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Return-to-service record",
    "dependency": "Repair complete",
    "automationRule": "Restore availability",
    "failure": "Unverified asset used",
    "kpi": "Verified Return-to-Service %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EQP-007",
    "fn": "Equipment Preventive Maintenance",
    "subFn": "Equipment",
    "subProcess": "Asset Control",
    "activity": "AMC/warranty monitoring",
    "standard": "Upcoming expiry surfaced",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Configured lead time",
    "origin": "RECURRING",
    "engine": "EQUIPMENT",
    "doer": "System/Manager",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Alert",
    "dependency": "Asset master",
    "automationRule": "Expiry reminder",
    "failure": "Coverage expires unnoticed",
    "kpi": "AMC/Warranty Coverage %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "EMR-001",
    "fn": "Emergency Management",
    "subFn": "Emergency",
    "subProcess": "Readiness & Response",
    "activity": "Daily emergency quick check",
    "standard": "Critical emergency equipment/items ready",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Opening",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Assistant",
    "checker": "Doctor/Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Assistant",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Pass/fail",
    "dependency": "Emergency master",
    "automationRule": "Critical exception",
    "failure": "Readiness failed",
    "kpi": "Emergency Readiness %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EMR-002",
    "fn": "Emergency Management",
    "subFn": "Emergency",
    "subProcess": "Readiness & Response",
    "activity": "Monthly full emergency audit",
    "standard": "Complete emergency inventory/function/expiry audit",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Scheduled",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinic Manager",
    "checker": "Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Clinical Director",
      "Owner"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Audit",
    "dependency": "Emergency master",
    "automationRule": "Findings/CAPA",
    "failure": "Major/critical gap",
    "kpi": "Emergency Audit Score",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EMR-003",
    "fn": "Emergency Management",
    "subFn": "Emergency",
    "subProcess": "Readiness & Response",
    "activity": "Emergency event documentation",
    "standard": "Every medical emergency creates incident record",
    "trigger": "EVENT",
    "frequency": "PER_EVENT",
    "dueRule": "Immediate/after stabilization",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Treating Team",
    "checker": "Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Clinical Director",
      "Clinic Head",
      "Owner"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Incident record",
    "dependency": "Emergency event",
    "automationRule": "Incident workflow",
    "failure": "Event undocumented",
    "kpi": "Emergency Incident Documentation %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "EMR-004",
    "fn": "Emergency Management",
    "subFn": "Emergency",
    "subProcess": "Readiness & Response",
    "activity": "Emergency drill",
    "standard": "Team drill completed per schedule",
    "trigger": "TIME",
    "frequency": "QUARTERLY",
    "dueRule": "Scheduled",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinic Manager",
    "checker": "Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Clinical Director",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Drill record",
    "dependency": null,
    "automationRule": "Training/competency update",
    "failure": "Drill overdue/failed",
    "kpi": "Emergency Drill Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "TRN-001",
    "fn": "Staff Training & Competency",
    "subFn": "People",
    "subProcess": "Training & Competency",
    "activity": "Role competency assignment",
    "standard": "Each role has required competency profile",
    "trigger": "MANUAL",
    "frequency": "ON_ROLE_CHANGE",
    "dueRule": "At assignment",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Manager",
    "checker": "Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Role competency map",
    "dependency": "Role assigned",
    "automationRule": "Gap analysis",
    "failure": "Required competency undefined",
    "kpi": "Role Competency Coverage %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "TRN-002",
    "fn": "Staff Training & Competency",
    "subFn": "People",
    "subProcess": "Training & Competency",
    "activity": "Training assignment",
    "standard": "Competency gap generates training/reassessment",
    "trigger": "EVENT",
    "frequency": "AS_REQUIRED",
    "dueRule": "On gap detection",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "System/Manager",
    "checker": "Trainer",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Trainer",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Training task",
    "dependency": "Gap detected",
    "automationRule": "Generate training",
    "failure": "Gap unaddressed",
    "kpi": "Training Completion %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "TRN-003",
    "fn": "Staff Training & Competency",
    "subFn": "People",
    "subProcess": "Training & Competency",
    "activity": "Competency assessment",
    "standard": "Skill assessed and level recorded with validity",
    "trigger": "EVENT",
    "frequency": "PER_ASSESSMENT",
    "dueRule": "Before independent work",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Qualified Assessor",
    "checker": "Clinical Director/Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Assessor",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Assessment evidence",
    "dependency": "Training complete",
    "automationRule": "Update competency",
    "failure": "Assessment missing",
    "kpi": "Competency Coverage %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "TRN-004",
    "fn": "Staff Training & Competency",
    "subFn": "People",
    "subProcess": "Training & Competency",
    "activity": "Restricted work gate",
    "standard": "Independent assignment requires minimum competency",
    "trigger": "DEPENDENCY",
    "frequency": "PER_ASSIGNMENT",
    "dueRule": "At assignment",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "System",
    "checker": "Manager",
    "owner": "Clinical Director",
    "escalation": [
      "Manager",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Gate result",
    "dependency": "Role competency",
    "automationRule": "Block/require supervision",
    "failure": "Underqualified assignment",
    "kpi": "Competency Gate Compliance %",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "TRN-005",
    "fn": "Staff Training & Competency",
    "subFn": "People",
    "subProcess": "Training & Competency",
    "activity": "Competency expiry monitoring",
    "standard": "Expiring credentials generate reassessment alert",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Lead-time configured",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "System",
    "checker": "Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Employee",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Alert",
    "dependency": "Validity date",
    "automationRule": "Generate reassessment",
    "failure": "Competency expires",
    "kpi": "Current Competency %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CON-001",
    "fn": "Professional Conduct",
    "subFn": "People",
    "subProcess": "Conduct",
    "activity": "Record conduct incident",
    "standard": "Material conduct issue recorded factually and confidentially",
    "trigger": "EVENT",
    "frequency": "AS_REQUIRED",
    "dueRule": "Promptly",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Manager",
    "checker": "Clinic Head",
    "owner": "Owner/Clinic Head",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Incident record",
    "dependency": null,
    "automationRule": "Review workflow",
    "failure": "Material issue not addressed",
    "kpi": "Conduct Incident Closure %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CON-002",
    "fn": "Professional Conduct",
    "subFn": "People",
    "subProcess": "Conduct",
    "activity": "Patient-facing conflict prevention",
    "standard": "No staff arguments/unprofessional conduct in patient areas",
    "trigger": "EVENT",
    "frequency": "CONTINUOUS",
    "dueRule": "Immediate",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "All Staff",
    "checker": "Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Incident if breach",
    "dependency": "Conduct policy",
    "automationRule": "Escalate breach",
    "failure": "Conflict in front of patient",
    "kpi": "Patient-Facing Conduct Incidents",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CON-003",
    "fn": "Professional Conduct",
    "subFn": "People",
    "subProcess": "Conduct",
    "activity": "Conduct follow-up",
    "standard": "Assigned corrective/coaching action completed",
    "trigger": "DEADLINE",
    "frequency": "PER_INCIDENT",
    "dueRule": "By due date",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Employee/Manager",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Action record",
    "dependency": "Conduct incident",
    "automationRule": "Overdue escalation",
    "failure": "Action overdue",
    "kpi": "Conduct Action Closure %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CMP-001",
    "fn": "Complaints",
    "subFn": "Quality",
    "subProcess": "Complaint Management",
    "activity": "Register complaint",
    "standard": "Every complaint captured with channel/category/severity",
    "trigger": "EVENT",
    "frequency": "PER_COMPLAINT",
    "dueRule": "At receipt",
    "origin": "PATIENT_EVENT",
    "engine": "PATIENT_EVENT",
    "doer": "Reception/Manager",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Complaint record",
    "dependency": null,
    "automationRule": "Assign owner/SLA",
    "failure": "Complaint unrecorded",
    "kpi": "Complaint Capture %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CMP-002",
    "fn": "Complaints",
    "subFn": "Quality",
    "subProcess": "Complaint Management",
    "activity": "Acknowledge complaint",
    "standard": "Patient acknowledgement within configured SLA",
    "trigger": "DEADLINE",
    "frequency": "PER_COMPLAINT",
    "dueRule": "SLA-defined",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Complaint Owner",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Acknowledgement",
    "dependency": "Complaint received",
    "automationRule": "SLA alert",
    "failure": "Acknowledgement overdue",
    "kpi": "Complaint Acknowledgement Time",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CMP-003",
    "fn": "Complaints",
    "subFn": "Quality",
    "subProcess": "Complaint Management",
    "activity": "Investigate complaint",
    "standard": "Facts reviewed and action documented",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_COMPLAINT",
    "dueRule": "Within SLA",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Complaint Owner",
    "checker": "Clinic Head",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Clinic Head",
      "Owner/Director"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Investigation",
    "dependency": "Acknowledged",
    "automationRule": "Escalate serious",
    "failure": "Investigation overdue",
    "kpi": "Complaint Resolution Time",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CMP-004",
    "fn": "Complaints",
    "subFn": "Quality",
    "subProcess": "Complaint Management",
    "activity": "Close complaint",
    "standard": "Resolution and patient contact documented",
    "trigger": "DEPENDENCY",
    "frequency": "PER_COMPLAINT",
    "dueRule": "Within SLA",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Complaint Owner",
    "checker": "Clinic Head",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Resolution/contact",
    "dependency": "Action complete",
    "automationRule": "Close workflow",
    "failure": "Closure incomplete",
    "kpi": "Complaint Closure %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INC-001",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Report incident",
    "standard": "Safety/quality incident recorded promptly",
    "trigger": "EVENT",
    "frequency": "PER_INCIDENT",
    "dueRule": "Immediate",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Any Authorized User",
    "checker": "Manager/Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Reporter",
      "Manager/Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Incident record",
    "dependency": null,
    "automationRule": "Severity routing",
    "failure": "Critical incident unreported",
    "kpi": "Incident Reporting Time",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "INC-002",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Immediate containment",
    "standard": "Immediate risk controlled/documented",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_INCIDENT",
    "dueRule": "Immediate",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Incident Owner",
    "checker": "Clinical Director/Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Containment action",
    "dependency": "Incident reported",
    "automationRule": "Escalate",
    "failure": "Containment missing",
    "kpi": "Containment Time",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "INC-003",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Root cause analysis",
    "standard": "Root cause category and analysis completed",
    "trigger": "STATUS_CHANGE",
    "frequency": "PER_INCIDENT",
    "dueRule": "By SLA",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Incident Owner",
    "checker": "Quality/Clinic Head",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Quality",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "RCA",
    "dependency": "Contained",
    "automationRule": "CAPA decision",
    "failure": "RCA overdue",
    "kpi": "RCA Completion %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "INC-004",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Create CAPA",
    "standard": "Required corrective/preventive actions assigned",
    "trigger": "DEPENDENCY",
    "frequency": "PER_INCIDENT",
    "dueRule": "After RCA",
    "origin": "GATE",
    "engine": "COMPLIANCE",
    "doer": "Quality/Manager",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Quality",
      "Clinic Head",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "CAPA record",
    "dependency": "CAPA required",
    "automationRule": "Create actions",
    "failure": "Required CAPA absent",
    "kpi": "CAPA Initiation %",
    "capa": "ALWAYS",
    "enabled": true
  },
  {
    "id": "INC-005",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Implement CAPA",
    "standard": "Actions completed by due date",
    "trigger": "DEADLINE",
    "frequency": "PER_CAPA",
    "dueRule": "Due date",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "CAPA Owner",
    "checker": "Quality/Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Quality",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Action evidence",
    "dependency": "CAPA open",
    "automationRule": "Overdue escalation",
    "failure": "CAPA overdue",
    "kpi": "CAPA On-Time Completion %",
    "capa": "ALWAYS",
    "enabled": true
  },
  {
    "id": "INC-006",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Effectiveness check",
    "standard": "CAPA effectiveness independently assessed",
    "trigger": "TIME",
    "frequency": "PER_CAPA",
    "dueRule": "Configured date",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Verifier",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Verifier",
      "Clinic Head",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Effectiveness result",
    "dependency": "Implemented",
    "automationRule": "Close/reopen",
    "failure": "Effectiveness overdue/ineffective",
    "kpi": "CAPA Effectiveness %",
    "capa": "ALWAYS",
    "enabled": true
  },
  {
    "id": "INC-007",
    "fn": "Incidents & CAPA",
    "subFn": "Quality",
    "subProcess": "Incident/CAPA",
    "activity": "Repeat failure detection",
    "standard": "Repeated same failure crosses threshold",
    "trigger": "THRESHOLD",
    "frequency": "CONTINUOUS",
    "dueRule": "Configured",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "System",
    "checker": "Quality/Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Quality",
      "Clinic Head",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Trend alert",
    "dependency": "Failure taxonomy",
    "automationRule": "Create/recommend incident/CAPA",
    "failure": "Repeat threshold exceeded",
    "kpi": "Repeat Failure Rate",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "AUD-001",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Weekly clinic health audit",
    "standard": "Weekly cross-domain audit completed",
    "trigger": "TIME",
    "frequency": "WEEKLY",
    "dueRule": "Week end",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinic Manager",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Audit score",
    "dependency": null,
    "automationRule": "Generate audit",
    "failure": "Audit overdue",
    "kpi": "Weekly Clinic Health Score",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "AUD-002",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Monthly operating review",
    "standard": "Monthly KPI/exception/CAPA review completed",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Month end",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinic Head",
    "checker": "Owner/Director",
    "owner": "Owner",
    "escalation": [
      "Clinic Head",
      "Owner",
      "Owner"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "ATTACHMENT",
    "evidenceRequired": "Review record",
    "dependency": "KPI data",
    "automationRule": "Generate review pack",
    "failure": "Review overdue",
    "kpi": "Monthly Review Compliance %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "AUD-003",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Infection control audit",
    "standard": "Detailed infection-control audit completed",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Scheduled",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinical/Quality Lead",
    "checker": "Clinical Director",
    "owner": "Clinic Head",
    "escalation": [
      "Auditor",
      "Clinical Director",
      "Clinic Head"
    ],
    "priority": "PATIENT_SAFETY",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Audit findings",
    "dependency": null,
    "automationRule": "Create findings/CAPA",
    "failure": "Major/critical finding",
    "kpi": "Infection Control Audit Score",
    "capa": "REQUIRED_ON_CRITICAL",
    "enabled": true
  },
  {
    "id": "AUD-004",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Equipment audit",
    "standard": "Asset status/PM/calibration reviewed",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Scheduled",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Clinic Manager",
    "checker": "Clinic Head",
    "owner": "Owner",
    "escalation": [
      "Manager",
      "Clinic Head",
      "Owner"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Audit",
    "dependency": null,
    "automationRule": "Create findings",
    "failure": "PM/calibration gaps",
    "kpi": "Equipment Compliance Score",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "AUD-005",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Inventory audit",
    "standard": "Critical stock/expiry/variance reviewed",
    "trigger": "TIME",
    "frequency": "MONTHLY",
    "dueRule": "Scheduled",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Inventory Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Audit/count",
    "dependency": null,
    "automationRule": "Create variance findings",
    "failure": "Material variance/expiry",
    "kpi": "Inventory Accuracy %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "AUD-006",
    "fn": "Weekly/Monthly Audits",
    "subFn": "Quality",
    "subProcess": "Audit Program",
    "activity": "Audit finding closure",
    "standard": "Findings closed by severity-based SLA",
    "trigger": "DEADLINE",
    "frequency": "PER_FINDING",
    "dueRule": "SLA-defined",
    "origin": "CONDITION",
    "engine": "EXCEPTION",
    "doer": "Finding Owner",
    "checker": "Auditor/Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Owner",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "VERIFICATION",
    "evidenceRequired": "Closure evidence",
    "dependency": "Finding open",
    "automationRule": "Escalate/CAPA",
    "failure": "Finding overdue",
    "kpi": "Audit Finding Closure %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLS-001",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Patient/appointment closure",
    "standard": "All visits/appointments reconciled at day end",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Reception",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Reception",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Reconciliation",
    "dependency": null,
    "automationRule": "Closing exception",
    "failure": "Open/unreconciled visit",
    "kpi": "Daily Reconciliation %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "CLS-002",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Lab day-end review",
    "standard": "All lab dispatch/receipt/status changes recorded",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Lab Coordinator",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Coordinator",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Status review",
    "dependency": null,
    "automationRule": "Closing exception",
    "failure": "Unrecorded lab movement",
    "kpi": "Lab Record Completeness %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "CLS-003",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Stock/critical consumables closing check",
    "standard": "Critical shortages identified before next day",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Inventory/Assistant",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Inventory",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Check",
    "dependency": "Tomorrow schedule",
    "automationRule": "Alert/PR",
    "failure": "Next-day shortage risk",
    "kpi": "Next-Day Stock Readiness %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLS-004",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Utilities shutdown",
    "standard": "Unused AC/lights/fans/equipment switched off safely",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "ROUTINE",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Closing checklist",
    "dependency": null,
    "automationRule": "Generate task",
    "failure": "Utility left on",
    "kpi": "Closing Compliance %",
    "capa": "NONE",
    "enabled": true
  },
  {
    "id": "CLS-005",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Water pump/tank check",
    "standard": "Pump safely switched off when tank full/at closing",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Assigned Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "IMPORTANT",
    "evidenceType": "CONFIRMATION",
    "evidenceRequired": "Checklist",
    "dependency": null,
    "automationRule": "Generate task",
    "failure": "Pump left on/issue",
    "kpi": "Facility Compliance %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  },
  {
    "id": "CLS-006",
    "fn": "Closing & Facility",
    "subFn": "Closing",
    "subProcess": "End-of-Day",
    "activity": "Final clinic lock/security",
    "standard": "Required floors/rooms secured and closure recorded",
    "trigger": "TIME",
    "frequency": "DAILY",
    "dueRule": "Final closing",
    "origin": "RECURRING",
    "engine": "TIME",
    "doer": "Authorized Closing Staff",
    "checker": "Clinic Manager",
    "owner": "Clinic Head",
    "escalation": [
      "Doer",
      "Manager",
      "Clinic Head"
    ],
    "priority": "CRITICAL",
    "evidenceType": "SYSTEM",
    "evidenceRequired": "Closure timestamp",
    "dependency": null,
    "automationRule": "Closing workflow",
    "failure": "Clinic not secured",
    "kpi": "Secure Closing %",
    "capa": "REQUIRED_ON_REPEAT",
    "enabled": true
  }
] as const;

/** Activities in one function (control parameter). */
export const activitiesInFunction = (fn: string): LibraryActivity[] =>
  ACTIVITY_LIBRARY.filter((a) => a.fn === fn);

/** Activities raised by one engine. */
export const activitiesByEngine = (engine: string): LibraryActivity[] =>
  ACTIVITY_LIBRARY.filter((a) => a.engine === engine);

/** Activities of one object type. */
export const activitiesByOrigin = (origin: string): LibraryActivity[] =>
  ACTIVITY_LIBRARY.filter((a) => a.origin === origin);

/** Everything a role touches, in any of its four capacities. */
export const activitiesForRoleName = (name: string): LibraryActivity[] =>
  ACTIVITY_LIBRARY.filter((a) => a.doer === name || a.checker === name
    || a.owner === name || a.escalation.includes(name));

/** Distinct KPIs the library feeds. */
export const LIBRARY_KPIS: readonly string[] =
  [...new Set(ACTIVITY_LIBRARY.map((a) => a.kpi).filter((k): k is string => !!k))].sort();

/** Distinct functions, in matrix order. */
export const LIBRARY_FUNCTIONS: readonly string[] =
  [...new Set(ACTIVITY_LIBRARY.map((a) => a.fn))];
