/**
 * Controls drafted for matrix v3.0, and not yet in force.
 *
 * GENERATED by scripts/generate-proposed-controls.mjs from
 * docs/requirements/matrix-v3-proposals.tsv. Do not edit by hand — edit the register.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * Why this file exists at all
 * ─────────────────────────────────────────────────────────────────────────
 *
 * Matrix v2.0 is frozen, so none of these govern anything today. But the
 * owner has decided their escalation — a missed housekeeping round reaches
 * the Clinic Manager — and a decision that lives only in a spreadsheet is a
 * decision the app cannot show anybody. Carrying the proposals here lets a
 * screen say *"would reach the Clinic Manager once HK-001 is accepted"*
 * instead of the blunter and now-misleading *"nobody hears about this"*.
 *
 * The distinction the tests defend: a proposal is never a control. Nothing
 * here is returned by `ladderFor`, nothing here counts as `covers`, and
 * nothing here makes an ungoverned standard governed. See
 * tests/unit/proposed-controls.test.ts.
 *
 * Job titles are the register's own words, not RoleCode. "Staff/HK" is not a
 * role KuBi has, and guessing which one it meant would name the wrong person.
 */

/** One drafted control, exactly as the register states it. */
export interface ProposedControl {
  /** HK-001, MNT-002, … The id it would carry if accepted. */
  id: string;
  parameter: string;
  activity: string;
  /** What good looks like, in the owner's wording. */
  standard: string;
  /** Null where the register still says DECISION_REQUIRED. */
  frequency: string | null;
  /** Null where the register still says DECISION_REQUIRED. */
  dueRule: string | null;
  /** Accountable owner, as a job title. */
  owner: string;
  /** L1 → L2 → L3, as job titles. Decided, even where the schedule is not. */
  escalation: string[];
  /**
   * Register columns still marked DECISION_REQUIRED. Non-empty means this
   * proposal cannot be accepted into a v3.0 matrix yet, whatever else is
   * settled about it.
   */
  openDecisions: string[];
}

export const PROPOSED_CONTROLS: readonly ProposedControl[] = [
  {
    id: "HK-001",
    parameter: "Cleanliness & Housekeeping",
    activity: "Treatment-room cleaning",
    standard: "Clean before operations",
    frequency: "DAILY",
    dueRule: "Opening, between patients, and closing",
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-002",
    parameter: "Cleanliness & Housekeeping",
    activity: "Dental chair surfaces",
    standard: "Clean/disinfected",
    frequency: "DAILY",
    dueRule: "Opening, between patients, and closing",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-003",
    parameter: "Cleanliness & Housekeeping",
    activity: "Slabs/worktops",
    standard: "Clean/disinfected",
    frequency: "DAILY",
    dueRule: "Opening, between patients, and closing",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-004",
    parameter: "Cleanliness & Housekeeping",
    activity: "Mirrors/glass",
    standard: "Clean",
    frequency: "DAILY",
    dueRule: "Opening, between patients, and closing",
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-005",
    parameter: "Cleanliness & Housekeeping",
    activity: "Floors",
    standard: "Clean/dry",
    frequency: "DAILY",
    dueRule: "Opening, between patients, and closing",
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-006",
    parameter: "Cleanliness & Housekeeping",
    activity: "Door handles",
    standard: "Clean/disinfected",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-007",
    parameter: "Cleanliness & Housekeeping",
    activity: "Switches/high-touch surfaces",
    standard: "Clean",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-008",
    parameter: "Cleanliness & Housekeeping",
    activity: "Washbasins/faucets",
    standard: "Clean/functioning",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-009",
    parameter: "Cleanliness & Housekeeping",
    activity: "Toilets",
    standard: "Clean/hygienic",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-010",
    parameter: "Cleanliness & Housekeeping",
    activity: "Soap/hand wash",
    standard: "Available",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-011",
    parameter: "Cleanliness & Housekeeping",
    activity: "Toilet paper/tissue",
    standard: "Available",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Frequency", "Due Rule"],
  },
  {
    id: "HK-012",
    parameter: "Cleanliness & Housekeeping",
    activity: "Staff dining area",
    standard: "Clean",
    frequency: "DAILY",
    dueRule: "Closing",
    owner: "Clinic Manager",
    escalation: ["Staff/HK", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "HK-013",
    parameter: "Cleanliness & Housekeeping",
    activity: "Reception",
    standard: "Clean/organized",
    frequency: "DAILY",
    dueRule: "Opening",
    owner: "Clinic Manager",
    escalation: ["HK/Reception", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Sub-Process", "KPI"],
  },
  {
    id: "HK-014",
    parameter: "Cleanliness & Housekeeping",
    activity: "Plants",
    standard: "Watered according to schedule",
    frequency: null,
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["HK", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Sub-Process", "Frequency", "Due Rule", "KPI"],
  },
  {
    id: "RCR-001",
    parameter: "Room & Chair Readiness",
    activity: "Consumables ready for the day",
    standard: "Gloves, gauze, tissues, RVG sleeves and procedure consumables available",
    frequency: "DAILY",
    dueRule: "Opening",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "RCR-002",
    parameter: "Room & Chair Readiness",
    activity: "Procedure instruments available",
    standard: "Procedure-specific instruments present and sterile before the procedure",
    frequency: "PER_PROCEDURE",
    dueRule: "Before procedure",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "RCR-003",
    parameter: "Room & Chair Readiness",
    activity: "Chair and equipment operational",
    standard: "Chair, suction and attached equipment functional before patient seating",
    frequency: "DAILY",
    dueRule: "Opening",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "RCR-004",
    parameter: "Room & Chair Readiness",
    activity: "Reset chair after every patient",
    standard: "Chair reset and surfaces disinfected before the next patient is seated",
    frequency: "PER_PATIENT",
    dueRule: "At patient checkout",
    owner: "Clinic Manager",
    escalation: ["Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "MNT-001",
    parameter: "Facilities & Maintenance",
    activity: "Periodic fittings check",
    standard: "Doors, handles, washbasins, faucets, bathroom fittings checked and working",
    frequency: "WEEKLY",
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Due Rule"],
  },
  {
    id: "MNT-002",
    parameter: "Facilities & Maintenance",
    activity: "Electrical fittings check",
    standard: "Switches, extension boards and visible wiring checked for damage or heat",
    frequency: "WEEKLY",
    dueRule: null,
    owner: "Clinic Head",
    escalation: ["Clinic Manager", "Clinic Head", "Owner"],
    openDecisions: ["Due Rule"],
  },
  {
    id: "MNT-003",
    parameter: "Facilities & Maintenance",
    activity: "Clinic furniture check",
    standard: "Clinic furniture stable, undamaged and safe to use",
    frequency: "MONTHLY",
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Due Rule"],
  },
  {
    id: "MNT-004",
    parameter: "Facilities & Maintenance",
    activity: "Report a repair need",
    standard: "Plumbing, electrical or repair need reported the moment it is found",
    frequency: "PER_EVENT",
    dueRule: "Immediately on discovery",
    owner: "Clinic Manager",
    escalation: ["Clinic Manager", "Clinic Head", "Owner"],
    openDecisions: [],
  },
  {
    id: "UTL-001",
    parameter: "Facilities & Maintenance",
    activity: "Water pump and tank monitoring",
    standard: "Pump switched off once the tank is full; no overflow and no dry run",
    frequency: "DAILY",
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Due Rule"],
  },
  {
    id: "UTL-002",
    parameter: "Facilities & Maintenance",
    activity: "Unoccupied-room energy check",
    standard: "Lights, fans, AC and equipment off in rooms not in use",
    frequency: "TWO_HOURLY",
    dueRule: null,
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: ["Due Rule"],
  },
  {
    id: "IC-001",
    parameter: "Infection Control",
    activity: "Dental unit waterline flush",
    standard: "Waterlines flushed to protocol at opening and at closing",
    frequency: "DAILY",
    dueRule: "Opening and closing",
    owner: "Clinic Head",
    escalation: ["Senior Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "IC-002",
    parameter: "Infection Control",
    activity: "Suction line cleaning",
    standard: "Suction lines cleaned daily after the last patient",
    frequency: "DAILY",
    dueRule: "After the last patient",
    owner: "Clinic Head",
    escalation: ["Senior Assistant", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "IC-003",
    parameter: "Infection Control",
    activity: "General waste round",
    standard: "General waste bins emptied and relined; segregation from biomedical intact",
    frequency: "DAILY",
    dueRule: "Opening and closing",
    owner: "Clinic Manager",
    escalation: ["Housekeeping", "Clinic Manager", "Clinic Head"],
    openDecisions: [],
  },
  {
    id: "OPN-006",
    parameter: "Opening Readiness",
    activity: "Morning huddle",
    standard: "Team huddle held and the day set, within 10 minutes",
    frequency: "DAILY",
    dueRule: null,
    owner: "Clinic Head",
    escalation: ["Clinic Manager", "Clinic Head", "Owner"],
    openDecisions: ["Due Rule"],
  },
];

/** A drafted control by id, or null. Never falls back to a frozen control. */
export function proposalById(id: string): ProposedControl | null {
  return PROPOSED_CONTROLS.find((p) => p.id === id) ?? null;
}

/** Proposals that could be accepted today — nothing left to decide. */
export function readyToAccept(): ProposedControl[] {
  return PROPOSED_CONTROLS.filter((p) => p.openDecisions.length === 0);
}
