/**
 * The activity library — the PSS engine, browsable.
 *
 * Function → sub-function → activity → task → parameter → KPI → owner →
 * checker → escalation → evidence. Every one of those comes off the frozen
 * matrix; none of it is authored here, and the file it reads is generated by
 * `scripts/build-activity-library.mjs`.
 *
 * That matters beyond tidiness. Constitution rule 4 says one source of truth,
 * everything generated — and this repository was breaking its own rule: the
 * parameter model was hand-written and the client had no activity dictionary
 * at all. A hand-copy is a fork with a delay fuse, and prototype #1 had
 * already proved it by drifting.
 *
 * Lives inside Standards rather than as a new tab, because the instruction was
 * to add depth without changing navigation.
 */
import { useState } from 'react';
import {
  ACTIVITY_LIBRARY, LIBRARY_FUNCTIONS, type LibraryActivity,
} from '@kubi/contracts';

const ORIGIN: Record<string, string> = {
  RECURRING: 'or-time', PATIENT_EVENT: 'or-event',
  CONDITION: 'or-cond', GATE: 'or-gate', EXCEPTION: 'or-exc',
};
const ORIGIN_LABEL: Record<string, string> = {
  RECURRING: 'Scheduled', PATIENT_EVENT: 'Patient event',
  CONDITION: 'Condition', GATE: 'Gate', EXCEPTION: 'Overdue',
};
const PRIORITY: Record<string, string> = {
  PATIENT_SAFETY: 'pri-safety', CRITICAL: 'pri-critical',
  IMPORTANT: 'pri-important', ROUTINE: 'pri-routine',
};

export function ActivityLibrary() {
  const [fn, setFn] = useState<string | null>(null);
  const [open, setOpen] = useState<string | null>(null);
  const [q, setQ] = useState('');

  const term = q.trim().toLowerCase();
  const shown = ACTIVITY_LIBRARY.filter((a) => {
    if (fn && a.fn !== fn) return false;
    if (!term) return true;
    return `${a.id} ${a.activity} ${a.standard ?? ''} ${a.kpi ?? ''}`
      .toLowerCase().includes(term);
  });

  const disabled = ACTIVITY_LIBRARY.filter((a) => !a.enabled).length;

  return (
    <>
      <p className="screen-sub">
        {ACTIVITY_LIBRARY.length} activities across {LIBRARY_FUNCTIONS.length} functions,
        generated from the frozen matrix. Nothing here is hand-maintained.
        {disabled > 0 && ` ${disabled} ship disabled — no due rule has been decided.`}
      </p>

      <input
        className="al-search"
        type="search"
        placeholder="Search activities, standards, KPIs…"
        value={q}
        onChange={(e) => setQ(e.target.value)}
        aria-label="Search the activity library"
      />

      <div className="al-fns">
        <button
          className={`al-fn ${fn === null ? 'is-on' : ''}`}
          type="button"
          onClick={() => setFn(null)}
        >
          All
        </button>
        {LIBRARY_FUNCTIONS.map((f) => (
          <button
            key={f}
            className={`al-fn ${fn === f ? 'is-on' : ''}`}
            type="button"
            onClick={() => setFn(fn === f ? null : f)}
          >
            {f}
          </button>
        ))}
      </div>

      {shown.length === 0 ? (
        <p className="bf-empty">Nothing matches “{q}”.</p>
      ) : (
        <ul className="al-list">
          {shown.map((a) => (
            <li key={a.id}>
              <button
                className="al-row"
                type="button"
                onClick={() => setOpen(open === a.id ? null : a.id)}
                aria-expanded={open === a.id}
              >
                <span className={`al-rail ${PRIORITY[a.priority ?? ''] ?? 'pri-routine'}`} />
                <span className="al-main">
                  <span className="al-act">{a.activity}</span>
                  <span className="al-where">{a.fn} · {a.subFn}</span>
                </span>
                <span className={`bf-origin ${ORIGIN[a.origin] ?? 'or-cond'}`}>
                  {ORIGIN_LABEL[a.origin] ?? a.origin}
                </span>
                <span className="al-id">{a.id}</span>
              </button>
              {open === a.id && <Detail a={a} />}
            </li>
          ))}
        </ul>
      )}
    </>
  );
}

/** The full PSS chain for one activity. */
function Detail({ a }: { a: LibraryActivity }) {
  return (
    <div className="al-detail">
      {a.standard && <p className="al-standard">{a.standard}</p>}

      <dl className="why-chain">
        <div><dt>Function</dt><dd>{a.fn}</dd></div>
        <div><dt>Sub-function</dt><dd>{a.subFn ?? '—'}</dd></div>
        {a.subProcess && <div><dt>Sub-process</dt><dd>{a.subProcess}</dd></div>}
        <div><dt>Trigger</dt><dd>{a.trigger ?? '—'}</dd></div>
        <div><dt>Frequency</dt><dd>{a.frequency ?? '—'}</dd></div>
        {/* Null due rule is an unmade decision, said as one. */}
        <div>
          <dt>Due</dt>
          <dd className={a.dueRule ? '' : 'al-undecided'}>
            {a.dueRule ?? 'not decided — activity disabled'}
          </dd>
        </div>
      </dl>

      <div className="why-head">Who is responsible</div>
      <dl className="why-chain">
        <div><dt>Doer</dt><dd>{a.doer ?? '—'}</dd></div>
        <div>
          <dt>Checker</dt>
          {/* Null permits self-verification. It never means nobody checks. */}
          <dd>{a.checker ?? 'may verify their own'}</dd>
        </div>
        <div><dt>Owner</dt><dd>{a.owner ?? '—'}</dd></div>
      </dl>

      {a.escalation.length > 0 && (
        <>
          <div className="why-head">If it does not happen</div>
          <ol className="why-ladder">
            {a.escalation.map((who, i) => (
              <li key={who}><b>L{i + 1}</b> → {who}</li>
            ))}
          </ol>
        </>
      )}

      <div className="why-head">Evidence and consequence</div>
      <dl className="why-chain">
        <div><dt>Evidence</dt><dd>{a.evidenceType ?? '—'}</dd></div>
        {a.evidenceRequired && <div><dt>Required</dt><dd>{a.evidenceRequired}</dd></div>}
        {a.dependency && <div><dt>Blocked by</dt><dd>{a.dependency}</dd></div>}
        {a.failure && <div><dt>Counts as failed</dt><dd>{a.failure}</dd></div>}
        {a.capa && <div><dt>CAPA</dt><dd>{a.capa.replace(/_/g, ' ').toLowerCase()}</dd></div>}
      </dl>

      {/* The IF/THEN rule, as the matrix states it. */}
      {a.automationRule && (
        <p className="al-auto"><b>Automation</b> — {a.automationRule}</p>
      )}
      {a.kpi && <p className="why-kpi">Moves <b>{a.kpi}</b></p>}
    </div>
  );
}
